spring:
  application:
    name: serv39-trainruntask
    
  profiles:
    active: topics,sender,remote

  rabbitmq:
    host: 10.5.133.220
    port: 5672
    username: guest
    password: guest
    virtual-host: /

ats:
  serv:
    tag: 10.5.133.212

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.5.133.219:8761/eureka/
      
server:
  port: 60039
