spring:
  application:
    name: serv39-trainruntask
    
  zipkin:
    baseUrl: http://10.5.133.219:9411

  profiles:
    active: topics,sender,remote

  rabbitmq:
    host: 10.5.133.213
    port: 5672
    username: atsusr
    password: atspwd
    virtual-host: atshst

ats:
  serv:
    tag: 10.5.133.212

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.5.133.219:8761/eureka/
      
info:
  app:
    artifact: "@project.artifact@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-artifact: "@project.parent.artifact@"
    spring-boot-version: "@project.parent.version@"     

    
server:
  port: 60039